### ISSUE TITLE
Uncaught Error: Unable to parse bindings

### ISSUE THREAD

**Issue by falconair** [jamesfoster/knockout.observableDictionary#1]
I used the latest file in HEAD. 

Setup the bindings as follows (please ignore the irrelevant bits):

``` javascript
var viewModel = {
    fills : ko.observableArray(),
    symbols : {MSFT:0},
    symbol_totals : new ko.observableDictionary({}),
    addFill : function(fill){ 
        var sym = fill[55];
        var total = (sym in this.symbols) ? this.symbols[sym] : 0;
        total = total + new Number(fill['rate']);
        this.symbols[sym] = total;

        this.symbol_totals.set(sym,total);

        this.fills.push(fill);
    }
};

ko.applyBindings(viewModel);
```

I bind them as such:

``` html
<table id="symbol-totals" class="zebra-striped condensed-table">
   <thead>
       <tr><th>Symbol</th><th>Total Commission</th></tr>
   </thead>
   <tbody data-bind="foreach: symbol_totals.items">
       <tr>
           <td data-bind="key"></td>
           <td data-bind="value"></td>
       </tr>
   </tbody>
</table>
```

When I used the 0.1 version, I saw nothing. I mean no errors, no binding updates (as if I hadn't written any observableDictionary code). With the latest version, I see the following exception. Please note that I am updating data whenever websocket send me an update.

I am testing this on the latest version of chrome, on a windows 64 bit machine. I'm using knockout version 2.0.0.

---

knockout-2.0.0.js:6Uncaught Error: Unable to parse bindings.
Message: SyntaxError: Unexpected token };
Bindings value: key

**Comment by jamesfoster** [comment]
The problem here is your bindings. You're missing **text:**

``` html
    <td data-bind="text: key"></td>
    <td data-bind="text: value"></td>
```

Also there was a big change from 0.1, In 0.1 you looped over the dictionary itself like: `foreach: symbol_totals`. This was moved to the `items` property to allow overriding of the toJSON method. I've updated the readme to recommend using the latest.

**Comment by jamesfoster** [comment]
As an aside, you're storing the symbol totals twice. once in the `symbols` object and again in the `symbol_totals` observable dictionary. You could try something like this to get rid of the `symbols` object:

``` javascript
addFill : function(fill){ 
    var sym = fill[55];

    var total = this.symbol_totals.get(sym)(); // get returns an observable. so call it
    total = total + new Number(fill['rate']);

    this.symbol_totals.set(sym,total);

    this.fills.push(fill);
}
```

or even

``` javascript
addFill : function(fill){ 
    var sym = fill[55];

    var total = this.symbol_totals.get(sym);
    total(total() + new Number(fill['rate']));

    this.fills.push(fill);
}
```

In this second case you're _using_ the observable returned from `get` to both retrieve and update the total. As mentioned in the README, if the key doesn't exist in the dictionary then it is created.

**Comment by falconair** [comment]
I was using a different method of doing it before I discovered your code. I
just ended up smashing your code into mine, that's why you see the
duplication :)

I'll clean it out. Thanks!

**Comment by falconair** [comment]
Thanks for the response.
So I should add "text:" to the binding, and use the latest release (instead of 0.1)?

**Comment by jamesfoster** [comment]
yes. the 0.1 cut I did is out-dated.

In knockout `data-bind="key"` is invalid. You need to specify what you're binding it to.

See this jsfiddle for a working example:

http://jsfiddle.net/jamesfoster/3u9ES/

**Comment by falconair** [comment]
Thanks, that worked.
You should push to try to get this into the core knockout project.
This functionality belongs there!

On Tue, Jan 24, 2012 at 6:08 PM, James Foster
reply@reply.github.com
wrote:

**Comment by jamesfoster** [comment]
I've just merged this project with the core knockout project. Here's the pull request:

https://github.com/SteveSanderson/knockout/pull/292

Hopefully they'll include it :)
