### ISSUE TITLE
Can "value" be an object?

### ISSUE THREAD

**Issue by tspratt** [jamesfoster/knockout.observableDictionary#2]
All the examples use simple strings in the value property, But i would like to put a complex object in there.

Then in binding, dot-down to the desired property, or use knockouts inline function to build the display value.

Is this possible?  I will try it myself.

**Comment by IWannaBeAMillionaire** [comment]
If value is an object you have to first get the object using brackets and then you can use it as regular object (get properties and so on) e.g.:

data-bind="text: dictionary.get('key')().objectPropertyName"

**Comment by tspratt** [comment]
Thanks! (I probably should have known that)
