### ISSUE TITLE
How to use with Mapping plugin

### ISSUE THREAD

**Issue by devmondo** [jamesfoster/knockout.observableDictionary#3]
hi, 
great code, but how can i use this when i get my object from server using Mapping plugin ?

thanks in advanced.

**Comment by jamesfoster** [comment]
Hi

It's quite easy with the mapping plugin to override the creation of properties.

```
var obj = {
  props: {
    foo: 123,
    bar: 456,
    baz: 789
  }
};

var model = ko.mapping.fromJS(obj, {
  props: {
    create: function(options) {
      return new ko.observableDictionary(options.data);
    }
  }
}

ko.applyBindings(model);
```

In the above example `model.props` should be mapped to an observable dictionary.

**Comment by devmondo** [comment]
thank you very much for the solution
